local:
  template_dir: templates
  sources:
  - id: abc
    directory: abc
  destinations:
  - id: '123'
    source: abc
    directory: '123'
  - id: '456'
    source: abc
    directory: '456'
task_modules:
- pyauto.local.commands
tasks:
  copyabc123456:
  - init_workspace
  - dst_copytree,123
  - dst_copytree,456

